#!/bin/bash

DIR=$(dirname $(readlink -e $0)) 
source $DIR/src/vars

log_daemon_msg "Checking if root"
if [[ $EUID -eq 0 ]]; then
    log_failure_msg "Do not run as root" 
    exit 1
fi

cd ~

log_daemon_msg "Fixing /home permissions"
if sudo chown $UNAME:$UNAME -R /home/$UNAME >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

for GITURL in "${!USERGIT[@]}";
do
    # if folder does not exist, will checkout
    if [[ ! -d ${USERGIT["$GITURL"]} ]]; then
        log_daemon_msg "Cloning $GITURL into ${USERGIT["$GITURL"]}"
        if git clone -q $GITURL "${USERGIT["$GITURL"]}" >> $LOG 2>&1;
            then log_end_msg 0 else log_end_msg 1
        fi
    fi
done

log_daemon_msg "Installing oh-my-zsh ..."
if sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

log_daemon_msg "backing up /etc/passwd file..."
if sudo cp /etc/passwd /etc/passwd.bak >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

# sets shell to zsh
log_daemon_msg "Setting ZSH as permanent shell for $UNAME ..."
if sudo sed -i "s#/home/$UNAME:/bin/bash#/home/$UNAME:/bin/zsh#" /etc/passwd >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

log_daemon_msg "Setting up zshrc aliases"
if sh ~/zshrc/install >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

log_daemon_msg "Updating zshrc submodules "
cd ~/zshrc
if git submodule update --init >> $LOG 2>&1; 
    then log_end_msg 0 else log_end_msg 1
fi

# log_daemon_msg "Adding powerline-shell zsh function"
# if cat powerline-status-func.txt >> ~/.zshrc; 
#     then log_end_msg 0 else log_end_msg 1
# fi

log_daemon_msg "Setting up powerline shell"
if ~/./powerline-shell/install.py >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

# log_daemon_msg "Symlinking powerline-shell"
# if ln -s $HOME/powerline-shell/powerline-shell.py $HOME/powerline-shell.py >> $LOG 2>&1;
#     then log_end_msg 0 else log_end_msg 1
# fi

log_daemon_msg "Setting up tmux env"
if sh ~/tmux/install >> $LOG 2>&1;
    then log_end_msg 0 else log_end_msg 1
fi

# log_daemon_msg "Setting up rbenv environment variables ..."
# if echo "export RBENV_ROOT=/usr/local/share/rbenv\nexport PATH=\"$RBENV_ROOT/bin:$PATH\"\neval \"$(rbenv init - zsh)\"\nsource $RBENV_ROOT/completions/rbenv.zsh" >> ~/.zshrc;
#     then log_end_msg 0 else log_end_msg 1
# fi

log_daemon_msg "Running vim setup"
if sh ~/.vim/install >> $LOG 2>&1; 
    then log_end_msg 0 else log_end_msg 1
fi

hash -r
$SHELL

cd $PWD

echo "Setup is now complete!! You should probably reboot"
exit 0
