#!/bin/bash
# functions for setup process
#

function checkRoot {
     
    log_daemon_msg "Checking if root"
    if [[ $EUID -ne 0 ]]; then
        log_failure_msg "This script must be ran as root" 
        exit 1
    else
        log_end_msg 0
    fi
 
}
