#!/bin/bash
# Description: Run wget command to auto install (no git checkout)
# 
# To execute:
#
# $ wget --no-check-certificate https://raw.githubusercontent.com/dtrip/.ubuntu-server/master/src/installer -O - | bash > /dev/null


. /lib/init/vars.sh
. /lib/lsb/init-functions

LOC=/usr/local/src/.ubuntu-server

log_daemon_msg "Checking if root"
if [[ $EUID -ne 0 ]]; then
    log_failure_msg "This script must be run as root" 
    exit 1
else
    log_end_msg 0
fi

I=0
DIR=$(dirname `readlink -e -- $0`) 
PWD=$(pwd)


if [[ ! $(which git) ]]; then

    log_daemon_msg "Updating package list"
    if apt-get -qq -y --force-yes update ;
        then log_end_msg 0 else log_end_msg 1
    fi

    log_daemon_msg "Installing git from apt sources"
    if apt-get -y -qq --force-yes install git; then
        log_end_msg 0
    else
        log_end_msg 1
        exit 1
    fi
fi 


log_daemon_msg "Checking out repository"
if git clone -q https://github.com/dtrip/.ubuntu-server $LOC;
then
        log_end_msg 0 
    else
        log_end_msg 1
        exit 1
fi

printf "\n"
echo -ne "Starting Install. And...."

while [ $I -lt 3 ]
do
    sleep 1s;
    if [ $I -eq 0 ]; then
        echo -ne "here.."
    elif [ $I -eq 1 ]; then
        echo -ne "we.."
    elif [ $I -eq 2 ]; then
        echo -ne "go.."
        sleep 1s;
    else
        echo "."
    fi
    I=$[$I+1]
done

cd $LOC
bash $LOC/setup &
