#!/bin/bash

DIR=$(dirname $(readlink -e $0)) 
source $DIR/vars

log_daemon_msg "setting up pyenv-install"
if curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | sudo bash;
    then log_end_msg 0 else log_end_msg 1
fi

