#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


# Ubuntu's short release version name: trusty, utopic, etc..
REL=$(lsb_release -cs)

# Ubuntu's version number: 14.04, 14.10, 15.04 etc.
VER=$(lsb_release -sr)

# gets path of file being executed
DIR=$(dirname $(readlink -e $0))


source $DIR/functions

PWD=$(pwd)

BINPATH="/usr/local/bin"
SSHD="/etc/ssh/sshd_config"
LOG="/tmp/ubuntu-server-setup"
UNAME=$(whoami)
HOSTNAME=$(hostname)

# ensures log files are created and writable
touch $LOG
chmod 666 $LOG

MSFPATH='/usr/local/share/metasploit-framework'         # location of metapsploit installation
NMAPPATH='/usr/local/share/nmap'                        # location of nmap installation
MSFRVERSION='2.1.7'                                     # ruby version to install for metapsloit

PYENV_ROOT="${HOME}/.pyenv"
NMAPURL='https://svn.nmap.org/nmap-releases/nmap-6.47/' # SVN URL of nmap

# declares associative array
declare -A GIT

# array of git repos root user will clone and or install
GIT=(
    ['https://github.com/epsylon/ufonet.git']='/usr/local/share/ufonet'
    ['https://github.com/dtrip/sqlmap']='/usr/local/share/sqlmap'
    ['https://github.com/dtrip/metasploit-framework']=$MSFPATH
    ['https://github.com/dtrip/commix']='/usr/local/share/commix'
    ['https://github.com/dtrip/weevely3']='/usr/local/share/weevely3'
    ['https://github.com/dtrip/websploit']='/usr/local/share/websploit'
    ['https://github.com/sstephenson/rbenv.git']='/usr/local/share/rbenv'
    ['https://github.com/wpscanteam/wpscan.git']='/usr/local/share/wpscan'
    ['https://github.com/sstephenson/ruby-build.git']='/usr/local/share/ruby-build'
    ['https://github.com/Anonymous-Dev/Pyloris.git']='/usr/local/share/pyloris'
    ['https://github.com/rofl0r/proxychains-ng.git']='/usr/local/share/proxychains-ng'
)

declare -A PYENVGIT
PYENVGIT=(
    ["https://github.com/yyuu/pyenv.git"]="${PYENV_ROOT}"
    ["https://github.com/yyuu/pyenv-doctor.git"]="${PYENV_ROOT}/plugins/pyenv-doctor"
    ["https://github.com/yyuu/pyenv-installer.git"]="${PYENV_ROOT}/plugins/pyenv-installer"
    ["https://github.com/yyuu/pyenv-update.git"]="${PYENV_ROOT}/plugins/pyenv-update"
    ["https://github.com/yyuu/pyenv-virtualenv.git"]="${PYENV_ROOT}/plugins/pyenv-virtualenv"
    ["https://github.com/yyuu/pyenv-which-ext.git"]="${PYENV_ROOT}/plugins/pyenv-which-ext"
    ["https://github.com/dtrip/prezto.git"]="${HOME}/prezto"
)

# SVN repo's root user will checkout and or isntall
declare -A SVN

SVN=(
    ["${NMAPURL}"]='/usr/local/src'
)


# declares associative array
declare -A USERGIT

# user packages
USERGIT=(
    ['https://github.com/dtrip/vim']='~/.vim'
    ['https://github.com/dtrip/tmux']='~/tmux'
    ['https://github.com/dtrip/zshrc']='~/zshrc'
    ['https://github.com/dtrip/powerline']='~/.config/powerline'
    ['https://github.com/dtrip/powerline-shell']='~/powerline-shell'
)


PKG='vim tmux python-pip build-essential libpcap-dev libssl-dev git git-extras git-core ack-grep libyaml-dev libreadline-dev libsqlite3-dev sqlite3 freetds-dev freetds-bin libpq-dev libpcre3-dev libpqxx-dev liblinear-dev subversion dnsutils autoconf libbison-dev htop fail2ban zsh trash-cli iptraf iftop nethogs chkrootkit rkhunter python-dev python-pycurl libbz2-dev ruby-dev libio-socket-ssl-perl libnetpacket-perl libnet-pcap-perl libnet-rawip-perl libnet-dns-perl libdbd-sqlite3-perl libdbd-sqlite-perl exuberant-ctags secure-delete'
PIP='powerline-status netifaces slowloris virtualenv pycurl wafw00f'

#name of group for ruby users
RUBYGROUP='ruby'

