#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

source functions

# Ubuntu's short release version name: trusty, utopic, etc..
REL=$(lsb_release -cs)

# Ubuntu's version number: 14.04, 14.10, 15.04 etc.
VER=$(lsb_release -sr)

# gets path of file being executed
DIR=$(dirname $(readlink -e $0))

PWD=$(pwd)

BINPATH="/usr/local/bin"
SSHD="/etc/ssh/sshd_config"
LOG="/tmp/ubuntu-server-setup"
UNAME=$(whoami)
HOSTNAME=$(hostname)

# ensures log files are created and writable
touch $LOG
chmod 666 $LOG

MSFPATH='/usr/local/share/metasploit-framework' # location of metapsploit installation
MSFRVERSION='2.1.6' # ruby version to install for metapsloit

# declares associative array
declare -A GIT

GIT=(
    ['https://github.com/epsylon/ufonet.git']='/usr/local/share/ufonet'
    ['https://github.com/dtrip/sqlmap']='/usr/local/share/sqlmap'
    ['https://github.com/dtrip/metasploit-framework']=$MSFPATH
    ['https://github.com/dtrip/commix']='/usr/local/share/commix'
    ['https://github.com/dtrip/websploit']='/usr/local/share/websploit'
    ['https://github.com/sstephenson/rbenv.git']='/usr/local/share/rbenv'
    ['https://github.com/wpscanteam/wpscan.git']='/usr/local/share/wpscan'
    ['https://github.com/sstephenson/ruby-build.git']='/usr/local/share/ruby-build'
    ['https://github.com/Anonymous-Dev/Pyloris.git']='/usr/local/share/pyloris'
)

# declares associative array
declare -A USERGIT

USERGIT=(
    ['https://github.com/dtrip/vim']='~/.vim'
    ['https://github.com/dtrip/tmux']='~/tmux'
    ['https://github.com/dtrip/zshrc']='~/zshrc'
    ['https://github.com/dtrip/powerline-shell']='~/powerline-shell'
)


PKG='vim tmux python-pip build-essential libpcap-dev libssl-dev git git-extras git-core ack-grep libyaml-dev libreadline-dev libsqlite3-dev freetds-dev freetds-bin libpq-dev libpcre3-dev libpqxx-dev liblinear-dev subversion dnsutils autoconf libbison-dev htop fail2ban zsh trash-cli iptraf iftop nethogs chkrootkit rkhunter python-dev python-pycurl'
PIP='powerline-status netifaces slowloris'

#name of group for ruby users
RUBYGROUP='ruby'

